run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - api
  skip-dirs-use-default: true
  skip-files:
    - ".*\\_test\\.go$"
    - "wire\\_gen\\.go$"
    - "wire\\.go$"

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1029:"
      text: "SA1019:"
    - linters:
        - stylecheck
      text: "ST1003:"
      text: "ST1005:"
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - durationcheck
    - errcheck
    - exportloopref
    - govet
    - gosimple
    - gofmt
    - gofumpt
    - goconst
    - goimports
    - gomnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - varcheck
    - whitespace
    - wastedassign

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - stylrcheck
  # - wsl

linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments:
          - [ID]
  stylecheck:
    go: "1.16"
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS"]
    http-status-code-whitelist: ["200", "400", "404", "500"]
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
    ignore-tests: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true
  funlen:
    lines: 120
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  whitespace:
    multi-func: true
  lll:
    line-length: 160
  gomnd:
    # don't include the "operation", "argument" and "assign"
    checks: 
      - case
      - condition
      - return
  gocyclo:
    # recommend 10-20
    min-complexity: 20

