// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: v1/shorten.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UrlFull string `protobuf:"bytes,2,opt,name=url_full,json=urlFull,proto3" json:"url_full,omitempty"`
	UrlCode string `protobuf:"bytes,3,opt,name=url_code,json=urlCode,proto3" json:"url_code,omitempty"`
}

func (x *ShortenURL) Reset() {
	*x = ShortenURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURL) ProtoMessage() {}

func (x *ShortenURL) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURL.ProtoReflect.Descriptor instead.
func (*ShortenURL) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURL) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShortenURL) GetUrlFull() string {
	if x != nil {
		return x.UrlFull
	}
	return ""
}

func (x *ShortenURL) GetUrlCode() string {
	if x != nil {
		return x.UrlCode
	}
	return ""
}

type CreateShortenURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CreateShortenURLRequest) Reset() {
	*x = CreateShortenURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenURLRequest) ProtoMessage() {}

func (x *CreateShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortenURLReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortenUrl *ShortenURL `protobuf:"bytes,1,opt,name=shorten_url,json=shortenUrl,proto3" json:"shorten_url,omitempty"`
}

func (x *CreateShortenURLReply) Reset() {
	*x = CreateShortenURLReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenURLReply) ProtoMessage() {}

func (x *CreateShortenURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenURLReply.ProtoReflect.Descriptor instead.
func (*CreateShortenURLReply) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShortenURLReply) GetShortenUrl() *ShortenURL {
	if x != nil {
		return x.ShortenUrl
	}
	return nil
}

type GetShortenURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Query:
	//	*GetShortenURLRequest_Id
	//	*GetShortenURLRequest_Code
	Query isGetShortenURLRequest_Query `protobuf_oneof:"query"`
}

func (x *GetShortenURLRequest) Reset() {
	*x = GetShortenURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenURLRequest) ProtoMessage() {}

func (x *GetShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenURLRequest.ProtoReflect.Descriptor instead.
func (*GetShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{3}
}

func (m *GetShortenURLRequest) GetQuery() isGetShortenURLRequest_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (x *GetShortenURLRequest) GetId() int64 {
	if x, ok := x.GetQuery().(*GetShortenURLRequest_Id); ok {
		return x.Id
	}
	return 0
}

func (x *GetShortenURLRequest) GetCode() string {
	if x, ok := x.GetQuery().(*GetShortenURLRequest_Code); ok {
		return x.Code
	}
	return ""
}

type isGetShortenURLRequest_Query interface {
	isGetShortenURLRequest_Query()
}

type GetShortenURLRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetShortenURLRequest_Code struct {
	Code string `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

func (*GetShortenURLRequest_Id) isGetShortenURLRequest_Query() {}

func (*GetShortenURLRequest_Code) isGetShortenURLRequest_Query() {}

type GetShortenURLReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortenUrl *ShortenURL `protobuf:"bytes,1,opt,name=shorten_url,json=shortenUrl,proto3" json:"shorten_url,omitempty"`
}

func (x *GetShortenURLReply) Reset() {
	*x = GetShortenURLReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortenURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenURLReply) ProtoMessage() {}

func (x *GetShortenURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenURLReply.ProtoReflect.Descriptor instead.
func (*GetShortenURLReply) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{4}
}

func (x *GetShortenURLReply) GetShortenUrl() *ShortenURL {
	if x != nil {
		return x.ShortenUrl
	}
	return nil
}

type DecodeShortenURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DecodeShortenURLRequest) Reset() {
	*x = DecodeShortenURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeShortenURLRequest) ProtoMessage() {}

func (x *DecodeShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeShortenURLRequest.ProtoReflect.Descriptor instead.
func (*DecodeShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{5}
}

func (x *DecodeShortenURLRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DecodeShortenURLReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlFull string `protobuf:"bytes,1,opt,name=url_full,json=urlFull,proto3" json:"url_full,omitempty"`
}

func (x *DecodeShortenURLReply) Reset() {
	*x = DecodeShortenURLReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeShortenURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeShortenURLReply) ProtoMessage() {}

func (x *DecodeShortenURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeShortenURLReply.ProtoReflect.Descriptor instead.
func (*DecodeShortenURLReply) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{6}
}

func (x *DecodeShortenURLReply) GetUrlFull() string {
	if x != nil {
		return x.UrlFull
	}
	return ""
}

type DeleteShortenURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShortenURLRequest) Reset() {
	*x = DeleteShortenURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortenURLRequest) ProtoMessage() {}

func (x *DeleteShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortenURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{7}
}

type DeleteShortenURLReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShortenURLReply) Reset() {
	*x = DeleteShortenURLReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShortenURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortenURLReply) ProtoMessage() {}

func (x *DeleteShortenURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortenURLReply.ProtoReflect.Descriptor instead.
func (*DeleteShortenURLReply) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{8}
}

type ListShortenURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListShortenURLRequest) Reset() {
	*x = ListShortenURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortenURLRequest) ProtoMessage() {}

func (x *ListShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ListShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{9}
}

type ListShortenURLReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListShortenURLReply) Reset() {
	*x = ListShortenURLReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_shorten_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShortenURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortenURLReply) ProtoMessage() {}

func (x *ListShortenURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shorten_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortenURLReply.ProtoReflect.Descriptor instead.
func (*ListShortenURLReply) Descriptor() ([]byte, []int) {
	return file_v1_shorten_proto_rawDescGZIP(), []int{10}
}

var File_v1_shorten_proto protoreflect.FileDescriptor

var file_v1_shorten_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e,
	0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x0a, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c,
	0x46, 0x75, 0x6c, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x44, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0xfa, 0x42, 0x14, 0x72, 0x12, 0x32, 0x10,
	0x5e, 0x28, 0x68, 0x74, 0x74, 0x70, 0x7c, 0x68, 0x74, 0x74, 0x70, 0x73, 0x29, 0x3a, 0x2f, 0x2f,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x54, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b,
	0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52,
	0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x5e, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x05, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x0c, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x22, 0x51, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55,
	0x52, 0x4c, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x36,
	0x0a, 0x17, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55,
	0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x32, 0x0a, 0x15, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x46, 0x75, 0x6c, 0x6c, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xee,
	0x03, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x12, 0x62, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x27,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x62,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55,
	0x52, 0x4c, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x59, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x55, 0x52, 0x4c, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55,
	0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x12,
	0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x62, 0x0a, 0x10, 0x44,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x12,
	0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x1f, 0x5a, 0x1d, 0x75, 0x72, 0x6c, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_shorten_proto_rawDescOnce sync.Once
	file_v1_shorten_proto_rawDescData = file_v1_shorten_proto_rawDesc
)

func file_v1_shorten_proto_rawDescGZIP() []byte {
	file_v1_shorten_proto_rawDescOnce.Do(func() {
		file_v1_shorten_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_shorten_proto_rawDescData)
	})
	return file_v1_shorten_proto_rawDescData
}

var file_v1_shorten_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_shorten_proto_goTypes = []interface{}{
	(*ShortenURL)(nil),              // 0: api.shorten.v1.ShortenURL
	(*CreateShortenURLRequest)(nil), // 1: api.shorten.v1.CreateShortenURLRequest
	(*CreateShortenURLReply)(nil),   // 2: api.shorten.v1.CreateShortenURLReply
	(*GetShortenURLRequest)(nil),    // 3: api.shorten.v1.GetShortenURLRequest
	(*GetShortenURLReply)(nil),      // 4: api.shorten.v1.GetShortenURLReply
	(*DecodeShortenURLRequest)(nil), // 5: api.shorten.v1.DecodeShortenURLRequest
	(*DecodeShortenURLReply)(nil),   // 6: api.shorten.v1.DecodeShortenURLReply
	(*DeleteShortenURLRequest)(nil), // 7: api.shorten.v1.DeleteShortenURLRequest
	(*DeleteShortenURLReply)(nil),   // 8: api.shorten.v1.DeleteShortenURLReply
	(*ListShortenURLRequest)(nil),   // 9: api.shorten.v1.ListShortenURLRequest
	(*ListShortenURLReply)(nil),     // 10: api.shorten.v1.ListShortenURLReply
}
var file_v1_shorten_proto_depIdxs = []int32{
	0,  // 0: api.shorten.v1.CreateShortenURLReply.shorten_url:type_name -> api.shorten.v1.ShortenURL
	0,  // 1: api.shorten.v1.GetShortenURLReply.shorten_url:type_name -> api.shorten.v1.ShortenURL
	1,  // 2: api.shorten.v1.Shorten.CreateShortenURL:input_type -> api.shorten.v1.CreateShortenURLRequest
	7,  // 3: api.shorten.v1.Shorten.DeleteShortenURL:input_type -> api.shorten.v1.DeleteShortenURLRequest
	3,  // 4: api.shorten.v1.Shorten.GetShortenURL:input_type -> api.shorten.v1.GetShortenURLRequest
	9,  // 5: api.shorten.v1.Shorten.ListShortenURL:input_type -> api.shorten.v1.ListShortenURLRequest
	5,  // 6: api.shorten.v1.Shorten.DecodeShortenURL:input_type -> api.shorten.v1.DecodeShortenURLRequest
	2,  // 7: api.shorten.v1.Shorten.CreateShortenURL:output_type -> api.shorten.v1.CreateShortenURLReply
	8,  // 8: api.shorten.v1.Shorten.DeleteShortenURL:output_type -> api.shorten.v1.DeleteShortenURLReply
	4,  // 9: api.shorten.v1.Shorten.GetShortenURL:output_type -> api.shorten.v1.GetShortenURLReply
	10, // 10: api.shorten.v1.Shorten.ListShortenURL:output_type -> api.shorten.v1.ListShortenURLReply
	6,  // 11: api.shorten.v1.Shorten.DecodeShortenURL:output_type -> api.shorten.v1.DecodeShortenURLReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shorten_proto_init() }
func file_v1_shorten_proto_init() {
	if File_v1_shorten_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_shorten_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenURLReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortenURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortenURLReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeShortenURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeShortenURLReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShortenURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShortenURLReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShortenURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_shorten_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShortenURLReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_shorten_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetShortenURLRequest_Id)(nil),
		(*GetShortenURLRequest_Code)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_shorten_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_shorten_proto_goTypes,
		DependencyIndexes: file_v1_shorten_proto_depIdxs,
		MessageInfos:      file_v1_shorten_proto_msgTypes,
	}.Build()
	File_v1_shorten_proto = out.File
	file_v1_shorten_proto_rawDesc = nil
	file_v1_shorten_proto_goTypes = nil
	file_v1_shorten_proto_depIdxs = nil
}
