// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameURLShortened = "url_shortened"

// URLShortened mapped from table <url_shortened>
type URLShortened struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	URLFull   string `gorm:"column:url_full;not null" json:"url_full"`
	URLHost   string `gorm:"column:url_host;not null" json:"url_host"`
	URLURI    string `gorm:"column:url_uri;not null" json:"url_uri"`
	URLQuery  string `gorm:"column:url_query;not null" json:"url_query"`
	URLCode   string `gorm:"column:url_code;not null" json:"url_code"`
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt int64  `gorm:"column:deleted_at;not null;default:0" json:"deleted_at"`
}

// TableName URLShortened's table name
func (*URLShortened) TableName() string {
	return TableNameURLShortened
}
