// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"url-shorten/app/shorten/internal/conf"
	"url-shorten/app/shorten/internal/server"
	"url-shorten/app/shorten/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	shortenService := service.NewShortenService()
	grpcServer := server.NewGRPCServer(confServer, shortenService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
