server:
  http:
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/url_shorter?charset=utf8mb4&parseTime=True&loc=Local&timeout=1s&readTimeout=5s&writeTimeout=5s
    pool:
      max_idle: 10
      max_open: 100
      # 300s
      max_life_time: 300
  redis:
    addr: 127.0.0.1:6379
    db: 0
    password:
    # 1000ms
    dial_timeout: 1000
    # 200ms
    read_timeout: 200
    # 200ms
    write_timeout: 200
    # 5 min = 300 * 1000 ms
    idle_timeout: 300000
    # 1000ms (read_timeout+1)
    pool_timeout: 1200
    # no expire
    max_conn_age: 0
    pool_type: fifo
    pool_size: 50
    min_idle_conns: 5

